EmployeeManagement/Models/Department.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

public class Department {
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Code { get; set; }

    public string Description { get; set; }

    public DateTime StartDate { get; set; }

    public List<Person> People {get; set; }
}

EmployeeManagement/Models/ErrorViewModel.cs
using System;

namespace EmployeeManagement.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeeManagement/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

public class Person {

    public Person(){

    }
    public Person(int id, string firstName, string lastName, char gender, long contact, string address=default) {
        Id = id;
        FirstName = firstName;
        LastName = lastName;
        Address = address;
        Gender = gender;
        Contact = contact;
    }

    public int Id {get; set;}

    [Required]
    [Display(Name = "First Name")]
    public string FirstName {get; set;}

    [Display(Name = "Last Name")]
    public string LastName {get; set;}

    public string? Address {get; set; } = "Kapan, Kathmandu";

    public char Gender { get; set; }
    public long? Contact {get; set; }

    // public static List<Person> GetEmployee(){
    //     Person p1 = new Person(1, "Rajesh", "Pudasaini", 'M', 9860476499, "Bhaktapur");
    //     Person p2 = new Person(2, "Rajendra", "Pudasaini", 'M', 9860476499, "Syangja");
    //     Person p3 = new Person(3, "Kabita", "Pudasaini", 'F', 9860476499, "Kapan");
    //     Person p4 = new Person(4, "Krishna", "Pudasaini", 'F', 9860476499, "Kathmandu");
    //     Person p5 = new Person(5, "Sunil", "KC", 'M', 9860476499, "Baneshwor");

    //     List<Person> persons = new List<Person>{p1, p2, p3, p4, p5};
    //     return persons;
    // }

    public Department Department { get; set; }
    public int DepartmentId { get; set;}
}

EmployeeManagement/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;


public class DepartmentController: Controller 
{

    private readonly EMSContext db;
    public DepartmentController(EMSContext _db){
        //construction injection
        db = _db;
    }

    public ActionResult Index() {
        var departments = db.Department.ToList();
        // var persons = Person.GetEmployee();
        return View(departments);
    }

    public ActionResult Detail(int id){
        

        var p1 = db.Department.Find(id);
        return View(p1);
    }

    public ActionResult Add(){
        return View();
    }

    [HttpPost]
    public ActionResult Add(Department department){
        db.Department.Add(department);
        db.SaveChanges();
        // return Redirect("/employee");
        return RedirectToAction(nameof(Index));
    }

    public ActionResult Update(int id){

        var department = db.Department.Find(id);
        return View(department);
    }

    

    [HttpPost]
    public ActionResult Update(Department department){
        
        db.Department.Attach(department);
        db.Department.Update(department);
        db.SaveChanges();
        return RedirectToAction(nameof(Index));
    }

    public ActionResult Delete(int id){

        var department = db.Department.Find(id);
        return View(department);
    }

    [HttpPost]
    public ActionResult Delete(Department department){
        db.Department.Attach(department);
        db.Department.Remove(department);
        db.SaveChanges();
        return RedirectToAction(nameof(Index));
    }


}

EmployeeManagement/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;


public class EmployeeController: Controller 
{

    private readonly EMSContext db;
    public EmployeeController(EMSContext _db){
        //construction injection
        db = _db;
    }

    // public List<Person> persons = Person.GetEmployee();

    //listing employee list
    public ActionResult Index() {
        var persons = db.People.Include(x => x.Department).ToList();
        // var persons = Person.GetEmployee();
        return View(persons);
    }

    //listing employee detail
    //[FromQuery] is attribute
    // [Route("summary")] if we want to change url
    public ActionResult Detail(int id){
        // var persons = Person.GetEmployee();
        // Person p1 = null;
        // foreach(var p in persons){
        //     if (p.FirstName == firstName){
        //         p1 = p;
        //     }
        // }
        // if (p1 != null){
        //     return View(p1);
        // }
        // return View();
       
        // var p1 = from person in db.People
        //              where person.Id == id
        //              select person;

        var p1 = db.People.Find(id);

        // return View(p1.FirstOrDefault());
        return View(p1);
    }

    //view to add employee default is HTTPGET
    public ActionResult Add(){
        var departments = db.Department.ToList();
        ViewData["DepartmentOptions"] = departments; 
        return View();
    }

    [HttpPost]
    public ActionResult Add(Person person){
        db.People.Add(person);
        db.SaveChanges();
        // return Redirect("/employee");
        return RedirectToAction(nameof(Index));
    }

    public ActionResult Update(int id){

        var person = db.People.Find(id);
        return View(person);
    }

    [HttpPost]
    public ActionResult Update(Person person){
        
        db.People.Attach(person);
        db.People.Update(person);
        db.SaveChanges();
        return RedirectToAction(nameof(Index));
    }


    public ActionResult Delete(int id){

        var person = db.People.Find(id);
        return View(person);
    }

    [HttpPost]
    public ActionResult Delete(Person person){
        db.People.Attach(person);
        db.People.Remove(person);
        db.SaveChanges();
        return RedirectToAction(nameof(Index));
    }
    
}

EmployeeManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EmployeeManagement.Models;

namespace EmployeeManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeManagement/Views/Department/Add.cshtml
@model Department;
@{
    ViewData["Title"] = "Add Department";
}


<h3>Add New Department</h3>

<form asp-controller="Department" asp-action="Add" method="POST">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Name"></label>
            <span asp-validation-for="Name" class="text-danger"></span>
            <input type="text" class="form-control" asp-for="Name" placeholder="Name" required />
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Code"></label>
            <span class="text-danger" asp-validation-for="Code"></span>
            <input type="text" class="form-control" asp-for="Code" placeholder="Code" required />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Description"></label>
            <textarea type="text" class="form-control" asp-for="Description" placeholder="Description" ></textarea>
        </div>
    </div>
        <div class="form-group">
            <label asp-for="StartDate"></label>
            <input type="date" class="form-control" placeholder="StartDate" asp-for="StartDate" />
        </div>
        
    <button type="submit" class="btn btn-primary">Save Department</button>
</form>

EmployeeManagement/Views/Department/Delete.cshtml
@model Department 


<a href="/employee" class="float-left flex align-items">Go Back</a><br>
<h1>Are You Sure to delete this record?</h1>
<hr>
<div class="card">
    <div class="card-header bg-light">
        <h4>Name: @Model.Name</h4>
    </div>
    <div class="card-body">
        <p>Code: @Model.Code</p>
        <p>Description: @Model.Description</p>
        <p>Start Date: @Model.StartDate</p>
    </div>
</div>
<form asp-controller="Department" asp-action="Delete" method="POST">
    <input type="hidden" asp-for="Id">
    <button class="btn btn-danger" type="submit">Delete anyway</button>
</form>

EmployeeManagement/Views/Department/Detail.cshtml
@model Department 

@{
  ViewData["Title"] = "Department - " + @Model.Name;
}


<a href="/department" class="btn btn-sm btn-primary float-left flex align-items">Go Back</a>
<h1 class="ml-2">Department Detail</h1>
<hr>
<div class="card">
    <div class="card-header bg-light">
        <h4>Name: @Model.Name</h4>
    </div>
    <div class="card-body">
        <p>Description: @Model.Description</p>
        <p>Code: @Model.Code</p>
        <p>Start Date: @Model.StartDate</p>
    </div>
</div>

EmployeeManagement/Views/Department/Index.cshtml
@model List<Department>
@{
  ViewData["Title"] = "Department Record List";
}

<h1>All Department (@Model.Count)</h1>
<table class="table table-striped">
  <thead>
    <a asp-controller="Department" asp-action="Add"><button class="btn btn-sm btn-primary float-right">
        Add New
      </button></a>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Department Name</th>
      <th scope="col">Code</th>
      <th scope="col">Description</th>
      <th scope="col">Start Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    @{
      int i = 1;}
    @foreach (var department in Model)
    {

      <tr scope="row">
        <td>
          @(i++)
        </td>
        <td>
          @{
            string departmentName = department.Name;
          }
          <a href="/department/detail?id=@department.Id">@departmentName</a>
        </td>
        <td>@department.Code</td>
        <td>@department.Description</td>
        <td>@department.StartDate</td>
        <td><a href="/Department/Update?id=@department.Id" class="btn btn-sm btn-primary">Edit</a></td>
        <td>
          <a href="/Department/Delete?id=@department.Id" class="btn btn-sm btn-danger">
            Delete
          </a>
        </td>

      </tr>
      @* <div class="modal fade" id="delDepartment-@department.Id" tabindex="-1" role="dialog"
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form asp-controller="Department" asp-action="Delete" method="POST">
              <input type="hidden" asp-for="@department" />
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger">Yes</button>
              </div>
            </form>

          </div>
        </div>
      </div> *@
    }


  </tbody>
</table>

EmployeeManagement/Views/Department/Update.cshtml
@model Department;
@{
    ViewData["Title"] = "Update Department";
}

<h3>Add New Department</h3>

<form asp-controller="Department" asp-action="Update" method="POST">
    <div class="form-row">
        <input type="hidden" asp-for="Id" />

        <div class="form-group col-md-6">
            <label asp-for="Name"></label>
            <span asp-validation-for="Name" class="text-danger"></span>
            <input type="text" class="form-control" asp-for="Name" placeholder="Name" required />
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Code"></label>
            <span class="text-danger" asp-validation-for="Code"></span>
            <input type="text" class="form-control" asp-for="Code" placeholder="Code" required />
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Description"></label>
            <textarea type="text" class="form-control" asp-for="Description" placeholder="Description" ></textarea>
        </div>
    </div>
        <div class="form-group">
            <label asp-for="StartDate"></label>
            <input type="date" class="form-control" placeholder="StartDate" asp-for="StartDate" />
        </div>
        
    <button type="submit" class="btn btn-primary">Save Department</button>
</form>

EmployeeManagement/Views/Employee/Add.cshtml
@model Person;
@{
    ViewData["Title"] = "Add Employee";
}

@{
    string[] genders = {"Male", "Female", "others"};
    List<Department> depOptions = ViewData["DepartmentOptions"] as List<Department>;

}

<h3>Add New Employee</h3>

<form asp-controller="Employee" asp-action="Add" method="POST">
    <div class="form-row">
        <div class="form-group">
            <select asp-for="DepartmentId">
                <option value="">Select Department</option>
                @foreach (var dep in depOptions)
                {
                    <option value="@dep.Id">@dep.Name</option>
                }
            </select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="FirstName"></label>
            <span asp-validation-for="FirstName" class="text-danger"></span>
            <input type="text" class="form-control" asp-for="FirstName" placeholder="First Name" required>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="LastName"></label>
            <span class="text-danger" asp-validation-for="LastName"></span>
            <input type="text" class="form-control" asp-for="LastName" placeholder="Last Name" required>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Gender"></label><br>
            @foreach (var gender in genders)
            {
                <input type="radio" asp-for="Gender" value="@gender[0]" /> @gender
            }
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Contact"></label>
            <input type="number" class="form-control" asp-for="Contact" placeholder="Contact Number">
        </div>
    </div>
    
        <div class="form-group">
            <label asp-for="Address"></label>
            <input type="text" class="form-control" placeholder="Address" asp-for="Address">
        </div>
        
    <button type="submit" class="btn btn-primary">Save Employee</button>
</form>

EmployeeManagement/Views/Employee/Delete.cshtml
@model Person 
@{
    var personFirstName = Model.FirstName;
    ViewData["Title"] = personFirstName;
}

<a href="/employee" class="float-left flex align-items">Go Back</a><br>
<h1>Are You Sure to delete this record?</h1>
<hr>
<div class="card">
    <div class="card-header bg-light">
        <h4>Name: @personFirstName @Model.LastName</h4>
    </div>
    <div class="card-body">
        <p>Gender: @Model.Gender</p>
        <p>Contact: @Model.Contact</p>
        <p>Address: @Model.Address</p>
    </div>
</div>
<form asp-controller="Employee" asp-action="Delete" method="POST">
    <input type="hidden" asp-for="Id">
    <button class="btn btn-danger" type="submit">Delete anyway</button>
</form>

EmployeeManagement/Views/Employee/Detail.cshtml
@model Person 
@{
    var personFirstName = Model.FirstName;
    ViewData["Title"] = personFirstName;
}

<a href="/employee" class="float-left flex align-items">Go Back</a>
<h1>Employee Detail</h1>
<hr>
<div class="card">
    <div class="card-header bg-light">
        <h4>Name: @personFirstName @Model.LastName</h4>
    </div>
    <div class="card-body">
        <p>Gender: @Model.Gender</p>
        <p>Contact: @Model.Contact</p>
        <p>Address: @Model.Address</p>
    </div>
</div>

EmployeeManagement/Views/Employee/Index.cshtml
@model List<Person>
@{
    ViewData["Title"] = "Employee Record List";
}

<h1>All Employee (@Model.Count)</h1>
<table class="table table-striped">
  <thead>
    <a asp-controller="Employee" asp-action="Add"><button class="btn btn-sm btn-primary float-right">
      Add New
    </button></a>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Gender</th>
      <th scope="col">Address</th>
      <th scope="col">Contact</th>
      <th scope="col">Department</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      @{int i=1;}
      @foreach (var person in Model )
      {
        
       <tr scope="row">
          <td>
            @(i++)
          </td>
            <td>
              @{
                  string employeeFirstName = person.FirstName;
              }
              <a href="/employee/detail?id=@person.Id">@employeeFirstName</a>
              </td>
            <td>@person.LastName</td>
            <td>@person.Gender</td>
            <td>@person.Address</td>
            <td>@person.Contact</td>
            <td>@person.Department.Name</td>
            <td><a href="/Employee/Update?id=@person.Id" class="btn btn-sm btn-primary">Edit</a></td>
            <td><a href="/Employee/Delete?id=@person.Id" class="btn btn-sm btn-danger">Delete</a></td>

        </tr>   
      }
    
    
  </tbody>
</table>

EmployeeManagement/Views/Employee/Update.cshtml
@model Person;
@{
    ViewData["Title"] = "Update Employee";
}

@{
    string[] genders = {"Male", "Female", "others"};
}

<h3>Update New Employee</h3>

<form asp-controller="Employee" asp-action="Update" method="POST">
    <div class="form-row">
        <input type="hidden" asp-for="Id" />
        <div class="form-group col-md-6">
            <label asp-for="FirstName"></label>
            <span asp-validation-for="FirstName" class="text-danger"></span>
            <input type="text" class="form-control" asp-for="FirstName" placeholder="First Name" required>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="LastName"></label>
            <span class="text-danger" asp-validation-for="LastName"></span>
            <input type="text" class="form-control" asp-for="LastName" placeholder="Last Name" required>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Gender"></label><br>
            @foreach (var gender in genders)
            {
                <input type="radio" asp-for="Gender" value="@gender[0]" /> @gender
            }
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Contact"></label>
            <input type="number" class="form-control" asp-for="Contact" placeholder="Contact Number">
        </div>
    </div>
    
        <div class="form-group">
            <label asp-for="Address"></label>
            <input type="text" class="form-control" placeholder="Address" asp-for="Address">
        </div>
        
    <button type="submit" class="btn btn-primary">Update Employee</button>
</form>

EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex  flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Employee
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Employee" asp-action="Index">List Employee</a>
                                
                                <a class="dropdown-item" asp-controller="Employee" asp-action="Add">Add Employee</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Department
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Department" asp-action="Index">List Department</a>
                                <a class="dropdown-item" asp-controller="Department" asp-action="Add">Add Employee</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EmployeeManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>